Provide safe wrappers for thread notification API
flipperzero-rs/flipperzero pull request #190
Opened 2024-11-15 05:48 UTC by dcoles

Furi provides access to [FreeRTOS Task Notification](https://freertos.org/Documentation/02-Kernel/02-Kernel-features/03-Direct-to-task-notifications/01-Task-notifications) feature which can be used for syncronization between threads.

Task notifications act as `u32` bitmask, so can be used to signal multiple potential interesting states on the target thread.

2024-11-22 18:31 UTC, JarvisCraft requested changes

2024-11-22 18:31 UTC, JarvisCraft commented on crates/flipperzero/src/furi/thread.rs
> +    /// The thread pointer must be non-null and point to a valid `FuriThread`.
```suggestion
    /// # Safety
    ///
    /// The thread pointer must be non-null and point to a valid `FuriThread`.
```

Minor markdown fix

2024-11-22 18:31 UTC, JarvisCraft commented on crates/flipperzero/src/furi/thread.rs
>  pub struct ThreadId(sys::FuriThreadId);
Let's add `#[repr(transparent)]` to it

2024-11-22 18:31 UTC, JarvisCraft commented on crates/flipperzero/src/furi/thread.rs
> +    let options = FuriFlag_FuriFlagWaitAny | (if !clear { FuriFlag_FuriFlagNoClear } else { 0 });
```suggestion
    let options = FuriFlag_FuriFlagWaitAny | (if clear { 0 } else { FuriFlag_FuriFlagNoClear });
```

Given overall expression complexity, getting rid of inversion seems useful

2024-11-22 18:31 UTC, JarvisCraft commented on crates/flipperzero/src/furi/thread.rs
> +    let options = FuriFlag_FuriFlagWaitAll | (if !clear { FuriFlag_FuriFlagNoClear } else { 0 });
```suggestion
    let options = FuriFlag_FuriFlagWaitAll | (if clear { 0 } else { FuriFlag_FuriFlagNoClear });
```

Same as above

2024-11-23 05:57 UTC, dcoles commented
@JarvisCraft Thanks for the review. I've accepted your suggestions and added the `repr(transparent)` annotation.

2024-11-23 10:58 UTC, JarvisCraft approved these changes

2024-11-24 01:34 UTC, merged