Update to SDK 34.3 (Firmware 0.87.0)
flipperzero-rs/flipperzero pull request #93
Opened 2023-07-24 21:03 UTC by avisbisk

Followed the docs to generate bindings and get this working locally on my system. Not sure if this is helpful, but figured I would create a PR incase this is. I didn't update the crate version in README, but I added the process changes that I needed to the updating-sdk docs. 
There was also a change with mod.rs, not sure what the root of the change was but looks like dolphin_deed only accepts one param as the deed.

2023-07-24 22:25 UTC, JarvisCraft requested changes

2023-07-24 22:25 UTC, JarvisCraft commented on crates/flipperzero/src/dolphin/mod.rs
> +        unsafe { sys::dolphin_deed(deed.to_raw())};
```suggestion
        unsafe { sys::dolphin_deed(deed.to_raw()) };
```

2023-08-09 23:17 UTC, str4d commented
I'll review this tomorrow (now that I have some time again for Flipper Zero stuff).

2023-08-10 13:45 UTC, JarvisCraft commented
@str4d, I will soon open the actualized version of this PR with for `0.88`

2023-08-10 14:01 UTC, closed without merging