feat: bump firmware version to 0.88.0
flipperzero-rs/flipperzero pull request #94
Opened 2023-08-10 13:58 UTC by JarvisCraft

# Description

This updates firmware version to `0.88.0`.

This also formats CHANGELOG.md to match the recommendation.

# Creditds

This is based on #86 and #93 by @kpmy and @avisbisk respectively.

2023-08-10 14:51 UTC, str4d commented
AFAICT this PR was unnecessary, as the SDK version did not change between 0.87.0 and 0.88.0. In any case, the versions should reference 0.87.0 instead (or mention both).

2023-08-10 15:30 UTC, str4d commented on crates/sys/src/bindings.rs
I compared this PR to #93, and aside from the documentation differences, I see this change in the bindings:
```diff
diff --git a/crates/sys/src/bindings.rs b/crates/sys/src/bindings.rs
index d853e27..5ce586c 100644
--- a/crates/sys/src/bindings.rs
+++ b/crates/sys/src/bindings.rs
@@ -1756,8 +1756,8 @@ extern "C" {
     pub fn strlcpy(
         arg1: *mut core::ffi::c_char,
         arg2: *const core::ffi::c_char,
-        arg3: core::ffi::c_uint,
-    ) -> core::ffi::c_uint;
+        arg3: usize,
+    ) -> usize;
 }
 extern "C" {
     pub static _ctype_: [core::ffi::c_char; 0usize];
@@ -2061,8 +2061,8 @@ pub const FuriThreadPriority_FuriThreadPriorityNormal: FuriThreadPriority = 16;
 pub const FuriThreadPriority_FuriThreadPriorityHigh: FuriThreadPriority = 17;
 #[doc = "Highest\n\n"]
 pub const FuriThreadPriority_FuriThreadPriorityHighest: FuriThreadPriority = 18;
-#[doc = "Deffered Isr (highest possible)\n\n"]
-pub const FuriThreadPriority_FuriThreadPriorityIsr: FuriThreadPriority = 32;
+#[doc = "Deferred ISR (highest possible)\n\n"]
+pub const FuriThreadPriority_FuriThreadPriorityIsr: FuriThreadPriority = 31;
 #[doc = "FuriThreadPriority\n\n"]
 pub type FuriThreadPriority = core::ffi::c_uchar;
 #[repr(C)]
@@ -7135,6 +7135,7 @@ pub type FuriHalVersionOtpVersion = core::ffi::c_uint;
 pub const FuriHalVersionColor_FuriHalVersionColorUnknown: FuriHalVersionColor = 0;
 pub const FuriHalVersionColor_FuriHalVersionColorBlack: FuriHalVersionColor = 1;
 pub const FuriHalVersionColor_FuriHalVersionColorWhite: FuriHalVersionColor = 2;
+pub const FuriHalVersionColor_FuriHalVersionColorTransparent: FuriHalVersionColor = 3;
 #[doc = "Device Colors\n\n"]
 pub type FuriHalVersionColor = core::ffi::c_uchar;
 pub const FuriHalVersionRegion_FuriHalVersionRegionUnknown: FuriHalVersionRegion = 0;
```

- The change to `strlcpy` is the same one we've seen and discussed before (https://github.com/flipperzero-rs/flipperzero/pull/65#issuecomment-1543329606 and https://github.com/flipperzero-rs/flipperzero/pull/70#discussion_r1197753541); please manually revert it, or generate the bindings using the Docker pathway to (hopefully) generate consistent bindings.
- The addition of `FuriHalVersionColor_FuriHalVersionColorTransparent` is probably fine to have; I presume firmware 0.87.0 will just ignore it.
- The change to the definition of `FuriThreadPriority_FuriThreadPriorityIsr` may or may not be a breaking change, I don't know. The fact that it happened without a bump in the SDK version is problematic, because we can't assume the two are identical and would instead need to save both variants and check the firmware version to confirm which is intended. If there is an upstream reference that can clarify whether perhaps the 0.87.0 version was a bug, that would help.

2023-08-10 15:35 UTC, str4d commented
I upgraded my Flipper Zero to 0.88.0 and tried running the unit tests from this branch; the harness is failing to run. We will need to figure out which of the intervening firmwares broke it.

2023-08-10 15:38 UTC, JarvisCraft commented on CHANGELOG.md
> +The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
Fair enough

it was my inaccuracy while syncing with the upstream example

2023-08-10 16:32 UTC, JarvisCraft commented on crates/sys/src/bindings.rs
I've pushed the fixed bindings with `Docker`

2023-08-10 17:28 UTC, str4d commented on crates/sys/src/bindings.rs
After the update to build with Docker, I see the following diff between this PR and #93:
```diff
diff --git a/crates/sys/src/bindings.rs b/crates/sys/src/bindings.rs
index d853e27..8c56e4e 100644
--- a/crates/sys/src/bindings.rs
+++ b/crates/sys/src/bindings.rs
@@ -1770,7 +1770,8 @@ extern "C" {
         arg4: *const core::ffi::c_char,
     ) -> !;
 }
-pub type va_list = u32;
+pub type __gnuc_va_list = u32;
+pub type va_list = __gnuc_va_list;
 pub type FILE = __FILE;
 extern "C" {
     pub fn sscanf(
@@ -2061,8 +2062,8 @@ pub const FuriThreadPriority_FuriThreadPriorityNormal: FuriThreadPriority = 16;
 pub const FuriThreadPriority_FuriThreadPriorityHigh: FuriThreadPriority = 17;
 #[doc = "Highest\n\n"]
 pub const FuriThreadPriority_FuriThreadPriorityHighest: FuriThreadPriority = 18;
-#[doc = "Deffered Isr (highest possible)\n\n"]
-pub const FuriThreadPriority_FuriThreadPriorityIsr: FuriThreadPriority = 32;
+#[doc = "Deferred ISR (highest possible)\n\n"]
+pub const FuriThreadPriority_FuriThreadPriorityIsr: FuriThreadPriority = 31;
 #[doc = "FuriThreadPriority\n\n"]
 pub type FuriThreadPriority = core::ffi::c_uchar;
 #[repr(C)]
@@ -7135,6 +7136,7 @@ pub type FuriHalVersionOtpVersion = core::ffi::c_uint;
 pub const FuriHalVersionColor_FuriHalVersionColorUnknown: FuriHalVersionColor = 0;
 pub const FuriHalVersionColor_FuriHalVersionColorBlack: FuriHalVersionColor = 1;
 pub const FuriHalVersionColor_FuriHalVersionColorWhite: FuriHalVersionColor = 2;
+pub const FuriHalVersionColor_FuriHalVersionColorTransparent: FuriHalVersionColor = 3;
 #[doc = "Device Colors\n\n"]
 pub type FuriHalVersionColor = core::ffi::c_uchar;
 pub const FuriHalVersionRegion_FuriHalVersionRegionUnknown: FuriHalVersionRegion = 0;
```

The `c_uint`/`usize` issue goes away. It is replaced by a different issue that we already knew would happen at some point (https://github.com/flipperzero-rs/flipperzero/pull/70#discussion_r1199723419), so that's fine.

The other two issues remain, and I remain concerned that the SDK update is being built from 0.88.0, instead of 0.87.0 as in #93, while the two have identical SDK versions. I would prefer that we close this PR and merge #93 instead unless we can find a clear explanation as to why the change to `FuriThreadPriority_FuriThreadPriorityIsr` is necessary; and even if we do this, we should still have most of the documentation reference 0.87.0 (as that is the version that introduced this SDK version).

2023-08-10 17:34 UTC, str4d commented
> I upgraded my Flipper Zero to 0.88.0 and tried running the unit tests from this branch; the harness is failing to run. We will need to figure out which of the intervening firmwares broke it.

I downgraded my Flipper Zero to 0.84.1 and confirmed that the unit tests do still work with that firmware version on the `main` branch. Identifying and addressing the issue is a blocker for this PR.

2023-08-11 15:26 UTC, str4d commented
I bisected the firmware updates and determined that the unit test harness stopped working due to the Application loader refactor. I confirmed locally that after updating to be aware of the change, the unit tests still pass on this PR, so it is no longer blocked (I will open a separate PR after this one to update the FAP runner tool appropriately).

2023-08-11 15:31 UTC, str4d requested changes

2023-08-11 15:31 UTC, str4d commented on CHANGELOG.md
> +- Migrated to SDK API 34.3 (firmware 0.88.0).
```suggestion
- Migrated to SDK API 34.3 (firmware 0.87.0).
```

2023-08-11 15:31 UTC, str4d commented on CHANGELOG.md
> +- Migrated to SDK API 28.2 (firmware 0.88.0).
Bug: this line should not have been altered.
```suggestion
- Migrated to SDK API 28.2 (firmware 0.84.1).
```

2023-08-11 15:31 UTC, str4d commented on README.md
> +[![Flipper Zero API](https://img.shields.io/badge/Flipper%20Zero%20API-34.3-orange)](https://github.com/flipperdevices/flipperzero-firmware/blob/0.88.0/firmware/targets/f7/api_symbols.csv)
This can stay referencing 0.88.0 due to the one extra symbol.

2023-08-11 15:31 UTC, str4d commented on README.md
> +Currently supports SDK 34.3 ([flipperzero-firmware@0.88.0](https://github.com/flipperdevices/flipperzero-firmware/tree/0.88.0)).
```suggestion
Currently supports SDK 34.3 ([flipperzero-firmware@0.87.0](https://github.com/flipperdevices/flipperzero-firmware/tree/0.87.0)).
```

2023-08-11 15:31 UTC, str4d commented on README.md
> +| 0.11.x        | 34.3        |
Before 0.11 is released, we should not imply that a particular API version will be in that release (API 35.0 was just released in 0.89.0-rc, so it's possible we'll end up doing another bump before 0.11).
```suggestion
| Unreleased    | 34.3        |
```

2023-08-11 15:33 UTC, str4d approved these changes

2023-08-11 15:39 UTC, merged